/*jshint unused: false*/

var VIEW = {
	NOTEBOOKS_LIST : 0,
	NOTES_LIST : 1,
	NOTEBOOK_NOTES : 2,
	TAGS : 3,
	USER : 4,
	EDIT_NOTE : 5,
	CIRCLE_PROGRESS : 6,
	SMALL_PROCESSING : 7,
	SETTINGS_MENU : 8,
	NOTES_TAG : 9,
	NOTE_CONTENT : 10,
	SELECT_NOTEBOOK : 11,
	CHANGE_NOTE_TAGS : 12
};